CREATE TABLE some (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    email UNIQUE NOT NULL,
    price INT,
    rating FLOAT PRECISION,
    CONSTRAINT price_validation CHECK (price > 0),
    CONSTRAINT rating_validation CHECK (rating > 0)
);

-- PRIMARY KEY in postgres is what we use in a table so that that particular field can be uniquly identified, and postgres can automatically anhance it because it's a special constraint, by adding UNIQUE constraint and NOT NULL constraint. (You can argue that NOT NULL isn't a constraint, but at the end of the day, it acts like one).

-- It is a way of us telling postgres that this is that unique column/property using which you can internally improve the performance etc and I can easily manipulate the table. (WHERE needs something unique and specific, remember ?).



-- Always use INT GENERATED ALWAYS AS IDENTITY instead of SERIAL, BIGSERIAL.
-- And for tight control over the auto-increment (that if you wnat to insert some of the values yourself), use INT GENERATED BY DEFAULT AS IDENTITY.
-- this is because SERIAL is rigid and can't be overriden, it's older and not recommended anymore.



-- Composite primary key : 

    CREATE TABLE cpk (
        user_id INT, -- this can't be auto-incrementing if we are going to use composite primary keys.
        movie_id INT,
        added_at TIMESTAMPTZ DEFAULT NOW(),
        -- PRIMARY KEY (user_id, movie_id)
    );

    ALTER TABLE cpk ADD CONSTRAINT cpk_key PRIMARY KEY (user_id, movie_id);

